---
title:       "RUSTSEC-2020-0074: pyo3: Reference counting error in `From<Py<T>>`"
description: "A bug in FromPyT would lead to an extra reference count decrement, often leading to useafterfree issues."
date:        2020-11-28
tags:        pyo3 memory-corruption
permalink:   /advisories/RUSTSEC-2020-0074:output_ext
---

### Description

A bug in `From<Py<T>>` would lead to an extra reference count decrement, often
leading to use-after-free issues.

### More Info

<https://github.com/PyO3/pyo3/pull/1297>

### Patched Versions

- `>=0.12.4`



### Unaffected Versions

- `<0.12.0`
